# Generated by Django 3.1.2 on 2021-01-11 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctores',
            fields=[
                ('iddoctores', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('cedula', models.IntegerField()),
                ('especialidad', models.CharField(blank=True, default=None, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HabitosCepillado',
            fields=[
                ('idHabitosCepillado', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Apellido', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Cedula', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Edad', models.DateField()),
                ('Correo', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Direccion', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('Ocupacion', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculo')], max_length=1)),
                ('Motivo', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('fecha_ini', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('idTelefonos', models.AutoField(primary_key=True, serialize=False)),
                ('movil', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('casa', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Paciente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('idOtros', models.AutoField(primary_key=True, serialize=False)),
                ('B_otros', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], max_length=1)),
                ('Frecuencia', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Otros_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.habitoscepillado')),
            ],
        ),
        migrations.CreateModel(
            name='Odontodiagrama',
            fields=[
                ('idOdontodiagrama', models.AutoField(primary_key=True, serialize=False)),
                ('caries', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Paciente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Intrabucal',
            fields=[
                ('idIntrabucal', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('Paciente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='habitoscepillado',
            name='Paciente_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente'),
        ),
        migrations.CreateModel(
            name='Fuma',
            fields=[
                ('idFuma', models.AutoField(primary_key=True, serialize=False)),
                ('B_fuma', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], max_length=1)),
                ('Forma', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Fuma_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.habitoscepillado')),
            ],
        ),
        migrations.CreateModel(
            name='foto',
            fields=[
                ('idfoto', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Paciente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraBucal',
            fields=[
                ('idExtraBucal', models.AutoField(primary_key=True, serialize=False)),
                ('Perfil', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Piel_Mucosa', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('ATM', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('otros', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Paciente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoOdontologico',
            fields=[
                ('idDiagnosticoOdontologico', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('Paciente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('idconsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Tratamiento', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Abono', models.IntegerField(blank=True, null=True)),
                ('Resta', models.IntegerField(blank=True, null=True)),
                ('sucursal', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('ProximaCita', models.DateTimeField(blank=True, null=True)),
                ('doctores_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.doctores')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('idCafe', models.AutoField(primary_key=True, serialize=False)),
                ('B_cafe', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], max_length=1)),
                ('Duracion', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Cafe_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.habitoscepillado')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesMedicos',
            fields=[
                ('idAntecedentes', models.AutoField(primary_key=True, serialize=False)),
                ('Personales', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Familiares', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Alergicos', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Hemorragias', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('otras', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('Paciente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
    ]
